# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [docker, instagram]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username Snaker.io
ko_fi: # Replace with a single Ko-fi username purple
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm install --save-dev flow-remove-types
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username HANNA
issuehunt: # Replace with a single IssueHunt username SANS
otechie: # Replace with a single Otechie username IANNA
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://magnoliaelectricpower.com','https://pampers.com','https://Newport-pleasure.com']
https://www.facebook.com/Kiss-MY-ASS-109439763884582/
